config/routes.rb
Rails.application.routes.draw do
  #Root Path
  root to: "main#index"

  get "admin", to: "admin#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "section", to: "admin#index"
  get "section/edit", to: "admin#edit", as: :section_edit
  patch "section", to: "admin#update"
  get "section/:name", to: "admin#show", as: :section_show
  delete "section/:name", to: "admin#delete", as: :section_delete
  get "section_new", to: "admin#new"
  post "section_new", to: "admin#create"

  resources :students do
    resources :interviews
  end

  patch "students/:id/apply", to: "students#apply", as: "student_apply"
  get "/appliedstudents", to: "students#applied", as: "applied_students"
  get "payments", to: "students#payments", as: "list_students_payment"

  # resources :eligibles
  get "eligibles/:id/edit", to: "eligibles#edit", as: :edit_eligibles
  patch "eligibles/:id", to: "eligibles#update", as: :eligible
  get "eligibles/:section_id", to: "eligibles#new", as: :new_eligible
  post "eligibles/:section_id", to: "eligibles#create"
  delete "eligibles/:id", to: "eligibles#destroy", as: :delete_eligible

  post "/", to: "main#notify"

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"

  delete "logout", to: "sessions#destroy"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :section
  belongs_to :user
  has_many :interviews
  has_one_attached :photo
  has_many_attached :marksheets

  enum status: {
    not_reviewed: 0,
    scheduled: 1,
    selected: 2,
    rejected: 3,
  }

  validates :name, :father, :mother, format: { with: /\A[A-Za-z ]+\z/, message: "only letters are allowed" }
  validates :name, presence: { message: " cannot be blank" }
  validates :father, presence: { message: "\'s name cannot be blank" }
  validates :mother, presence: { message: "\'s name cannot be blank" }
  validates :age, presence: true, numericality: { less_than: 20, message: " must be less than 20 years" }
  validates :address, presence: true
  validates :pnumber, presence: true, length: { in: 10..11, too_long: "%{count} digits is maximum allowed" }
  validates :prevgrade, presence: true
  validates :marksheets, presence: true, attached: true, content_type: { in: "application/pdf", message: "is not a PDF" }, size: { less_than: 5.megabytes, message: " is too large!" }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :require_user_logged_in!

  def index
    if (Current.user.admin == true)
      @student = Student.includes(:photo_attachment).order(:name)
    else
      @student = Current.user.students.includes(:photo_attachment)
    end
  end

  def applied
    if Current.user.admin == true
      @student = Student.where(applied: true)
    else
      @student = Current.user.students.where(applied: true)
    end
  end

  def new
    @student = Student.new
    @options = Section.where(value: true).map { |u| [u.name, u.id] }
  end

  def create
    @options = Section.where(value: true).map { |u| [u.name, u.id] }
    @student = Current.user.students.new(student_params)
    if @student.save
      redirect_to students_path, notice: "Successfully applied!"
      message = "Student named #{@student.name} has been added"
      notify(@student.user_id, message)
    else
      render :new, status: :unprocessable_entity
    end
    puts @student.to_json()
  end

  def show
    # binding.pry
    @student = Student.find_by(id: params[:id])
    student_login_auth_check
  end

  def edit
    @student = Student.find_by(id: params[:id])
    @options = Section.where(value: true).map { |u| [u.name, u.id] }
    if @student.applied == true
      redirect_to students_path, alert: "Application already submitted!"
    end
    student_login_auth_check
  end

  def update
    @student = Student.find_by(id: params[:id])
    @options = Section.where(value: true).map { |u| [u.name, u.id] }
    if Current.user.admin == false
      if @student.update(student_params)
        redirect_to students_path, notice: "Updated successfully!"
      else
        render :edit
      end
    else
      # binding.pry
      if @student.update(student_params)
        # binding.pry
        redirect_to students_path, notice: "Updated changes as an admin!"
      else
        render :edit
      end
    end
  end

  def destroy
    @student = Student.find_by(id: params[:id])
    if @student.destroy
      redirect_to students_path, notice: "Deleted successfully!"
    else
      render :index, alert: "Failed to delete application!"
    end
  end

  def apply
    @student = Student.find_by(id: params[:id])
    if @student.update(student_params)
      StudentMailer.with(user: @student.user.email).student_added.deliver_later
      redirect_back fallback_location: students_path, notice: "Applied Successfully!"
      message = "Application for #{@student.name} has been recieved."
      notify(@student.user_id, message)
    else
      render :show, alert: "Couldn't file application!"
    end
  end

  def payments
    @student = Current.user.students
  end

  private

  def student_params
    params.require(:student).permit(:name, :age, :father, :mother, :address, :pnumber, :applied, :prevgrade, :section_id, :user_id, :photo, marksheets: [])
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/applied.html.erb
<% if @student.length == 0 %>
  <h2>There are no applications filed.</h2>
<% else %>
  <div class="d-flex justify-content-center">
    <section class="card shadow my-3 text-white w-75 text-center p-3" style="background-color: rgba(114, 108, 248, 0.3);">
      <h1 class="h1 mt-3">List of Applications</h1>
      <h4 class="mt-2">No. of Applications: <%= @student.length %></h4>
      <div class="table-responsive">
        <table class="table align-middle text-white mt-3">
          <thead>
            <tr class="fs-5">
              <th scope="col">Student Name</th>
              <th scope="col">Section</th>
              <th scope="col">Status</th>
              <th scope="col">Interview Status</th>
              <th scope="col">Schedule Interview</th>
            </tr>
          </thead>
          <tbody>
            <% @student.includes(:section).each do |student| %>
              <tr class="fs-5 text-white">
                <td><%= link_to student.name, student_path(student), class: "text-decoration-none fs-5 text-white" %></td>
                <td><%= student.section.name.capitalize %></td>
                <td><%= student.status.capitalize.gsub("_", " ") %></td>
                <td><%= link_to "Status", student_interviews_path(student), class: "btn btn-warning" %></td>
                <td><%= link_to "Schedule", new_student_interview_path(student), class: "btn btn-info" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </section>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="d-flex justify-content-center">
  <% # binding.pry %>
  <%= form_with(model: @student, url: student_path(@student), method: :patch, local: true, html: { style: "min-width: 50%;" }) do |form| %>
  <% if @student.errors.any? %>
    <div class="mt-3 alert alert-danger alert-dismissable fade show" role="alert">
      <% @student.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
      <% end %>
    </div>
  <% end %>
  <section class="card my-5 shadow" style="background-color: rgba(114, 108, 248, 0.3);">
    <div class="card-body">
      <h3 class="card-title mb-4 text-white">Student application form</h3>
      <h6 class="card-subtitle mb-3 text-white">Application form for admission of a new student</h6>
      <div class="form-floating mb-3">
        <%= form.text_field :name, class: "form-control", placeholder: "Jane Doe" %>
        <%= form.label :name, "Full Name *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_field :father, class: "form-control", placeholder: "Jane Doe" %>
        <%= form.label :father, "Father's Name *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_field :mother, class: "form-control", placeholder: "Jane Doe" %>
        <%= form.label :mother, "Mother's Name *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.number_field :age, class: "form-control", placeholder: "10" %>
        <%= form.label :age, "Age *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_area :address, class: "form-control", style: "height: 150px;", placeholder: "Your address" %>
        <%= form.label :address, "Address *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.telephone_field :pnumber, class: "form-control", placeholder: "1234567890" %>
        <%= form.label :pnumber, "Phone number *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.number_field :prevgrade, step: :any, class: "form-control", placeholder: "9" %>
        <%= form.label :prevgrade, "Previous test marks in % *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.select :section_id, options_for_select(@options, @student.section_id), {}, { class: "form-select" } %>
        <%= form.label :section_id, "Section for admission *" %>
      </div>
      <div class="mb-3">
        <%= form.label :photo, "Profile Picture Upload", class: "form-label text-white" %>
        <%= form.file_field :photo, class: "form-control py-3" %>
      </div>
        <div class="mb-3">
        <%= form.label :marksheets, "Marksheet Upload *", class: "form-label text-white" %>
        <% if @student.marksheets.attached? %>
          <% @student.marksheets.includes(:blob).each do |marksheet| %>
          <%= marksheet.filename %>
          <% end %>
        <% end %>
        <%= form.file_field :marksheets, multiple: true, class: "form-control py-3" %>
      </div>
      <div class="d-flex text-center gap-3">
        <%= form.submit "Update", class: "button__student w-100" %>
        <%= link_to "Back", students_path, class: "button__student w-100" %>
      </div>
    </div>
  </section>
  <% end %>
</div>

app/views/students/index.html.erb
<% button__edits = "button__edit w-100" %>

<section class="my-5">
  <div class="d-flex flex-sm-row flex-column justify-content-center gap-4">
    <% @student.each do |student| %>
      <div class="text-center pt-3" 
        style="border-radius: 0.5rem; max-width: 200px;
        align-self: center;
        background: linear-gradient(to right bottom, rgba(246, 211, 101, 0.8), rgba(253, 160, 133, 0.8));">
        <%= image_tag student.photo, class: "img-fluid m-4", style: "width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" if student.photo.attached? %>
        <h4 class="mb-3" style="text-overflow: ellipsis; margin:auto;
          overflow: hidden; width: 150px; 
          height: 1.2em; white-space: nowrap;"><%= student.name %></h4>
        <div class="d-flex text-center gap-2 p-3">
        <% if (student.applied == true) %>
          <% button__edits += " btn__disable" %>
        <% else %>
          <% button__edits = "button__edit w-100" %>
        <% end %>
          <%= link_to "Edit", edit_student_path(student), class: button__edits, disabled: student.applied %>
          <%= link_to "Show", student_path(student), class: "button__student w-100" %>
        </div>
        <div class="pb-3 px-3"><%= link_to "Delete", student_path(student), method: :delete, class: "btn btn-danger w-100 p-2", style: "font-size: 1.2rem;" %></div>
      </div>
    <% end %> 
  </div>
</section>

app/views/students/new.html.erb
<div class="d-flex justify-content-center">
  <%= form_with(model: @student, url: students_path, local: true, html: { style: "min-width: 50%;" }) do |form| %>
  <% if @student.errors.any? %>
    <div class="mt-3 alert alert-danger alert-dismissable fade show" role="alert">
      <% @student.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
      <% end %>
    </div>
  <% end %>
  <section class="card my-5 shadow" style="background-color: rgba(114, 108, 248, 0.3);">
    <div class="card-body">
      <h3 class="card-title mb-4 text-white">Student application form</h3>
      <h6 class="card-subtitle mb-3 text-white">Application form for admission of a new student</h6>
      <h6 class="card-subtitle mb-3 text-white">* fields are mandatory</h6>
      <div class="form-floating mb-3">
        <%= form.text_field :name, class: "form-control", placeholder: "Jack Doe" %>
        <%= form.label :name, "Full Name *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_field :father, class: "form-control", placeholder: "John Doe" %>
        <%= form.label :father, "Father's Name *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_field :mother, class: "form-control", placeholder: "Jane Doe" %>
        <%= form.label :mother, "Mother's Name *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.number_field :age, class: "form-control", placeholder: "10" %>
        <%= form.label :age, "Age *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_area :address, class: "form-control", style: "height: 150px;", placeholder: "Your address" %>
        <%= form.label :address, "Address *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.telephone_field :pnumber, class: "form-control", placeholder: "1234567890" %>
        <%= form.label :pnumber, "Phone number *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.number_field :prevgrade, class: "form-control", placeholder: "9" %>
        <%= form.label :prevgrade, "Previous grade *" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.select :section_id, options_for_select(@options), {}, { class: "form-select" } %>
        <%= form.label :section_id, "Section for admission *" %>
      </div>
      <div class="mb-3">
        <%= form.label :photo, "Profile Picture Upload", class: "form-label text-white" %>
        <%= form.file_field :photo, class: "form-control py-3" %>
      </div>
      <div class="mb-3">
        <%= form.label :marksheets, "Marksheets Upload *", class: "form-label text-white" %>
        <%= form.file_field :marksheets, multiple: true, class: "form-control py-3" %>
      </div>
      <div class="d-flex text-center gap-3">
        <%= form.submit "Add Student", class: "button__student w-100" %>
        <%= link_to "Back", students_path, class: "button__student w-100" %>
      </div>
    </div>
  </section>
  <% end %>
</div>

app/views/students/payments.html.erb
<div class="d-flex justify-content-center">
  <section class="card shadow text-white" style="background-color: rgba(114, 108, 248, 0.1);">
    <div class="card-body">
      <h2 class="my-4"> Payment status for your applications</h2>
      <table class="table align-middle text-white">
        <thead>
          <tr>
            <th scope="col">Student Name</th>
            <th scope="col">Admission Fees</th>
            <% if Current.user.admin == false %><th scope="col">Action</th><% end %>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @student.each do |student| %>
            <tr>
              
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
</div>

app/views/students/show.html.erb
<% button__classes = "button__student" %>
<% button__edits = "button__edit" %>
<% button__delete = "btn btn-danger text-decoration-none text-white" %>
<% if @student.applied == true %>
  <% button__classes += " btn__disable" %>
  <% button__edits += " btn__disable" %>
  <% button__delete += " btn__disable" %>
<% end %>
  
<div class="d-flex flex-column justify-content-center align-items-center">
  <section class="card my-5 shadow" 
    style="background-color: rgba(114, 108, 248, 0.3); min-width: 60%; border-radius: 0.5rem;">
    <div class="row g-0">
      <div class="col-md-4 text-center pt-3" 
      style="border-radius: 0.5rem;
        background: linear-gradient(to right bottom, rgba(246, 211, 101, 0.8), rgba(253, 160, 133, 0.8));">
        <% if @student.photo.attached? %>
          <div class="d-flex flex-column justify-content-center align-items-center">
            <%= image_tag @student.photo, class: "img-fluid mt-5 mb-2", style: "width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" %>
            <%= button_to "Delete avatar", purge_attachment_path(@student.photo.id), method: :delete, class: button__delete + "text-decoration-none my-3 text-center", disabled: @student.applied %>
          </div>
        <% end %>
        <h2 class="mb-3 px-2"><%= @student.name %></h2>
        <h4 class="mb-3"><%= @student.section.name.capitalize %> Section</h4>
        <div class="d-flex text-center gap-2 p-3">
          <%= link_to "Edit", edit_student_path(@student), class: button__edits + " w-100", disabled: @student.applied %>
          <%= link_to "Back", students_path, class: "button__student w-100" %>
        </div>
        <div class="pb-3 px-3"><%= link_to "Delete", student_path(@student), method: :delete, class: "btn btn-danger w-100", style: "font-size: 1.2rem; padding: 0.8rem;" %></div>
        <div class="px-3 pb-3">
          <%= form_with(model: @student, url: student_apply_path(@student), method: :patch, local: true) do |form| %>
            <%= form.text_field :applied, value: true, hidden: true %>
            <%= form.submit "Apply Now", class: button__classes, style: "min-width: 100%;", disabled: @student.applied %>
          <% end %>
        </div>
      </div>
      <div class="mobile__adjust d-flex gap-3 flex-column justify-content-between col-md-8 p-4 text-white">
        <div class="row">
          <div class="col-6">
            <h5><strong>Father's Name:</strong></h5>
          </div>
          <div class="col-6">
            <h5><%= @student.father %></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <h5><strong>Mother's Name:</strong></h5>
          </div>
          <div class="col-6">
            <h5><%= @student.mother %></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <h5><strong>Age:</strong></h5>
          </div>
          <div class="col-6">
            <h5><%= @student.age %></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <h5><strong>Address:</strong></h5>
          </div>
          <div class="col-6">
            <h5><%= @student.address %></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <h5><strong>Phone:</strong></h5>
          </div>
          <div class="col-6">
            <h5><%= @student.pnumber %></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <h5><strong>Previous Grade:</strong></h5>
          </div>
          <div class="col-6">
            <h5><%= @student.prevgrade %></h5>
          </div>
        </div>
        <div class="row">
          <div class="align-middle col-6">
            <h5><strong>Marksheet Preview:</strong></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="d-flex gap-3 flex-column flex-sm-row justify-content-center align-items-center my-3">
              <% if @student.marksheets.attached? %>
                <% @student.marksheets.includes(:blob).each do |marksheet| %>
                  <div class="d-flex flex-column justify-content-center align-items-center">
                    <%= image_tag marksheet.preview(resize_to_fit: [150, 150]) %>
                    <%= button_to "Delete", purge_attachment_path(marksheet), method: :delete, class: button__delete + "text-center mt-3 fs-6", disabled: @student.applied %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>