config/routes.rb
Rails.application.routes.draw do
  #Root Path
  root to: "main#index"

  get "admin", to: "admin#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "section", to: "admin#index"
  get "section/edit", to: "admin#edit", as: :section_edit
  patch "section", to: "admin#update"
  get "section/:name", to: "admin#show", as: :section_show
  delete "section/:name", to: "admin#delete", as: :section_delete
  get "section_new", to: "admin#new"
  post "section_new", to: "admin#create"

  resources :students do
    resources :interviews
  end

  patch "students/:id/apply", to: "students#apply", as: "student_apply"
  get "/appliedstudents", to: "students#applied", as: "applied_students"
  get "payments", to: "students#payments", as: "list_students_payment"

  # resources :eligibles
  get "eligibles/:id/edit", to: "eligibles#edit", as: :edit_eligibles
  patch "eligibles/:id", to: "eligibles#update", as: :eligible
  get "eligibles/:section_id", to: "eligibles#new", as: :new_eligible
  post "eligibles/:section_id", to: "eligibles#create"
  delete "eligibles/:id", to: "eligibles#destroy", as: :delete_eligible

  post "/", to: "main#notify"

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"

  delete "logout", to: "sessions#destroy"
end

app/views/admin/edit.html.erb
<div class="d-flex justify-content-center" style="min-width: 50%;">
  <section class="card shadow" style="background-color: rgba(114, 108, 248, 0.3);">
    <div class="card-body text-white">
      <h2 class="my-4">Update admissions for the given sections:</h2>
      <p class="h5 mb-4">The following section shows the ongoing admissions for particuar sections. Update if necessary.</p>
      <%= form_for :@sec, url: section_path, html: { class: "form__container" }, method: :patch do |f| %>
        <% @sec.each do |section| %>
        <div class="form__main">
          <%= f.check_box :name, { multiple: true, checked: section[1] }, section[0], false %>
          <%= f.label section[0] %>
        </div>
        <% end %>
        <%= f.submit "Update", class: "button__student mt-3", style: "max-width: 100%;" %>
      <% end %>
    </div>  
  </section>
</div>

app/views/admin/index.html.erb
<div class="d-flex justify-content-center">
  <section class="card shadow text-white" style="background-color: rgba(114, 108, 248, 0.1);">
    <div class="card-body">
      <h2 class="my-4">List of all sections</h2>
      <div class="table-responsive">
        <table class="table align-middle text-white">
          <thead>
            <tr>
              <th scope="col">Section Name</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @sec.each do |sec| %>
              <tr>
                <td><%= sec[0].split.map(&:capitalize) * "" %></td>
                <td>
                <button type="button" class="btn btn-info me-2">
                  <%= link_to "Show ", section_show_path(sec[0]), class: "text-decoration-none text-dark" %>
                </button>
                <button type="button" class="btn btn-danger">
                  <%= link_to "Delete ", section_delete_path(sec[0]), method: :delete, class: "text-decoration-none text-white" %>
                </button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</div>

app/views/admin/new.html.erb
<%= form_with(model: @section, url: section_new_path, method: :post, local: true) do |form| %>
    <% if @section.errors.any? %>
      <div class="d-flex justify-content-center">
        <div class="alert alert-danger w-50 alert-dissmissable fade show mt-3 d-flex justify-content-between align-items-center" role="alert">
          <div>
            <% @section.errors.full_messages.each do |msg| %>
            <div><%= msg %></div>
            <% end %>
          </div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    <% end %>
  <div class="d-flex justify-content-center align-items-center">
    <section class="card text-white my-5 shadow" style="min-width: 25%; background-color: rgba(167,85,145, 0.7);">
      <div class="card-body">
        <h2 class="my-3 py-3">Add Section for admission</h2>
        <div class="form-floating mb-3">
          <%= form.text_field :name, class: "form-control", placeholder: "Name of the section" %>
          <%= form.label :name, "Section Name", class: "text-dark" %>
        </div>
        <div class="form-floating mb-3">  
          <%= form.select :value, options_for_select([["Admissions open", true], ["Admissions closed", false]], false), {}, { class: "form-select my-3" } %>
          <%= form.label :value, "Select the admission process", class: "text-dark" %>
        </div>
        <div class="form-floating mb-3">
        <%= form.number_field :fees, step: :any, class: "form-control", placeholder: "2000" %>
        <%= form.label :fees, "Admission Fees", class: "text-dark" %>
      </div>
        <div>
          <%= form.submit "Add Section", class: "button__student text-center" %>
        </div>
      </div>
    </section>
  </div>
<% end %>

app/views/admin/show.html.erb
<div class="d-flex justify-content-center">
  <section class="card shadow my-5 text-white p-3" style="background-color: rgba(114, 108, 248, 0.3);">
    <h1 class="h1 mt-5"><%= @section.name.split.map(&:capitalize) * "" %> Section</h1>
    <% if @section.value == false %>
      <p class="lead">Admissions are closed for this section at this moment.</p>
    <% else %>
      <p class="lead mt-6">Admissions are open for this section at this moment.</p>
    <% end %>
    <h2 class="my-3">Admission Fees</h2>
    <p class="lead mt-6">Rs. <%= @section.fees %></p>
    <% if @section.eligible.present? %>
    <h2 class="h2 my-3">Eligibility Criteria</h2>
      <div class="d-flex flex-column gap-3 justify-content-center">
        <div class="row">
          <div class="col-6 h5">Minimum age :</div>
          <div class="col-6 h5"><%= @section.eligible.age %></div>
        </div>
        <% if @section.eligible.grade != nil %>
          <div class="row">
            <div class="col-6 h5">Minimum grade :</div>
            <div class="col-6 h5"><%= @section.eligible.grade %> %</div>
          </div>
        <% end %>
        <div class="d-flex gap-3">
          <%= link_to "Update Criteria", edit_eligibles_path(@section.eligible), class: "button__student text-center w-100" %>
          <%= link_to "Delete Criteria", delete_eligible_path(@section.eligible), method: :delete, class: "button__student bg-danger text-center w-100" %>
        </div>
      </div>
    <% else %>
      <%= link_to "Add Criteria", new_eligible_path(@section.id), class: "button__student mt-3 w-100 text-center" %>
    <% end %>
  </section>
</div>