config/routes.rb
Rails.application.routes.draw do
  #Root Path
  root to: "main#index"

  get "admin", to: "admin#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "section", to: "admin#index"
  get "section/edit", to: "admin#edit", as: :section_edit
  patch "section", to: "admin#update"
  get "section/:name", to: "admin#show", as: :section_show
  delete "section/:name", to: "admin#delete", as: :section_delete
  get "section_new", to: "admin#new"
  post "section_new", to: "admin#create"

  resources :students do
    resources :interviews
  end

  patch "students/:id/apply", to: "students#apply", as: "student_apply"
  get "/appliedstudents", to: "students#applied", as: "applied_students"
  get "payments", to: "students#payments", as: "list_students_payment"

  # resources :eligibles
  get "eligibles/:id/edit", to: "eligibles#edit", as: :edit_eligibles
  patch "eligibles/:id", to: "eligibles#update", as: :eligible
  get "eligibles/:section_id", to: "eligibles#new", as: :new_eligible
  post "eligibles/:section_id", to: "eligibles#create"
  delete "eligibles/:id", to: "eligibles#destroy", as: :delete_eligible

  post "/", to: "main#notify"

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"

  delete "logout", to: "sessions#destroy"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <% if Current.user && Current.user.admin == true %>
    <% @path = admin_path %>
    <% else %>
    <% @path = root_path %>
    <% end %>
    <%= link_to "Admission", @path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", @path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Students", students_path, class: "nav-link" %>
        </li>
      </ul>
      <% if @path == root_path %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Add Student", new_student_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.name, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_section_form.html.erb
<%= form_for @section do |form| %>
  <% if @section.errors.any? %>
    <div class="alert alert-danger alert-dissmissable fade show" role="alert">
      <% @section.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
      <% end %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :name, "Section Name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Name of the section" %>
  </div>
  <div class="mb-3">  
    <%= form.label :value, "Select the admission process" %>
    <%= form.select :value, options_for_select([true, false]), class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Add Section", class: "btn btn-secondary" %>
  </div>
<% end %>