config/routes.rb
Rails.application.routes.draw do
  #Root Path
  root to: "main#index"

  get "admin", to: "admin#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "section", to: "admin#index"
  get "section/edit", to: "admin#edit", as: :section_edit
  patch "section", to: "admin#update"
  get "section/:name", to: "admin#show", as: :section_show
  delete "section/:name", to: "admin#delete", as: :section_delete
  get "section_new", to: "admin#new"
  post "section_new", to: "admin#create"

  resources :students do
    resources :interviews
  end

  patch "students/:id/apply", to: "students#apply", as: "student_apply"
  get "/appliedstudents", to: "students#applied", as: "applied_students"
  get "payments", to: "students#payments", as: "list_students_payment"

  # resources :eligibles
  get "eligibles/:id/edit", to: "eligibles#edit", as: :edit_eligibles
  patch "eligibles/:id", to: "eligibles#update", as: :eligible
  get "eligibles/:section_id", to: "eligibles#new", as: :new_eligible
  post "eligibles/:section_id", to: "eligibles#create"
  delete "eligibles/:id", to: "eligibles#destroy", as: :delete_eligible

  post "/", to: "main#notify"

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"

  delete "logout", to: "sessions#destroy"
end

app/models/eligible.rb
class Eligible < ApplicationRecord
  belongs_to :section

  validates :age, :grade, presence: { message: " cannot be blank" }
end

app/controllers/eligibles_controller.rb
class EligiblesController < ApplicationController
  before_action :require_admin_logged_in!

  def edit
    @eligible = Eligible.find_by(id: params[:id])
  end

  def update
    @eligible = Eligible.includes([:section]).find_by(id: params[:id])
    if @eligible.update(form_params)
      redirect_to section_path, notice: "Updated criteria successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @eligible = Eligible.find_by(id: params[:id])
    if @eligible.destroy
      redirect_to section_path, notice: "Deleted Criteria successfully!"
    else
      render :destroy, alert: "Failed to delete required criteria!"
    end
  end

  def create
    @section_id = params[:section_id]
    @eligible = Eligible.new(form_params)
    if @eligible.save
      redirect_to section_path, notice: "Added Eligibility Crteria!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @section_id = params[:section_id]
    @eligible = Eligible.new
  end

  private

  def form_params
    params.require(:eligible).permit(:age, :grade, :fees, :section_id)
  end
end

app/helpers/eligibles_helper.rb
module EligiblesHelper
end

app/views/eligibles/edit.html.erb
<div class="d-flex justify-content-center">
<%= form_with(model: @eligible, url: eligible_path(@eligible), method: :patch, html: { style: "min-width: 30%;" }) do |form| %>
  <% if @eligible.errors.any? %>
    <div class="mt-3 alert alert-danger alert-dismissable fade show" role="alert">
      <% @eligible.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
      <% end %>
    </div>
  <% end %>
  <section class="card shadow my-5 pt-4" style="background-color: rgba(114, 108, 248, 0.3);">
    <div class="card-body">
      <h3 class="card-title text-white mb-4"><%= Section.find_by(id: @eligible.section_id).name.capitalize %> Criteria Update</h3>
      <div class="form-floating mb-3">
        <%= form.text_field :age, class: "form-control", placeholder: "6" %>
        <%= form.label :age, "Minimum Age" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.text_field :grade, class: "form-control", placeholder: "40" %>
        <%= form.label :grade, "Minimum percentage" %>
      </div>
      <div class="d-flex text-center gap-3">
        <%= form.submit "Update", class: "button__student w-100" %>
        <%= link_to "Back", section_path, class: "button__student w-100" %>
      </div>
    </div>
  </section>
<% end %>
</div>

app/views/eligibles/new.html.erb
<div class="d-flex justify-content-center">
<%= form_with(model: @eligible, url: new_eligible_path(@section_id), local: true, html: { style: "min-width: 30%;" }) do |form| %>
  <% if @eligible.errors.any? %>
    <div class="mt-3 alert alert-danger alert-dismissable fade show" role="alert">
      <% @eligible.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
      <% end %>
    </div>
  <% end %>
  <section class="card shadow my-5 pt-4" style="background-color: rgba(114, 108, 248, 0.3);">
    <div class="card-body">
      <h3 class="card-title text-white mb-4"><%= Section.find_by(id: @section_id).name.capitalize %> Criteria Update</h3>
      <div class="form-floating mb-3">
        <%= form.number_field :age, step: :any, class: "form-control", placeholder: "6" %>
        <%= form.label :age, "Minimum Age" %>
      </div>
      <div class="form-floating mb-3">
        <%= form.number_field :grade, step: :any, class: "form-control", placeholder: "40" %>
        <%= form.label :grade, "Minimum percentage" %>
      </div>
      
      <%= form.hidden_field :section_id, class: "form-control", value: @section_id %>
      
      <div class="d-flex text-center gap-3">
        <%= form.submit "Add Criteria", class: "button__student w-100" %>
        <%= link_to "Back", section_path, class: "button__student w-100" %>
      </div>
    </div>
  </section>
<% end %>
</div>